language: minimal
dist: bionic

git:
  quiet: true

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /'
      key_url: 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_18.04/Release.key'
    update: true
    packages:
    - buildah

script:
- echo $quayiopassword | buildah login -u $quayiouser --password-stdin quay.io
- echo $githubtoken | buildah login -u $quayiouser --password-stdin docker.pkg.github.com
- sudo ./run.sh

after_success:
- sudo buildah push latex-builder:latest docker://quay.io/$quayiouser/latex-builder:latest
- sudo buildah push latex-builder:latest docker://docker.pkg.github.com/$quayiouser/latex-builder/latex-builder:latest

after_script:
- buildah logout quay.io
- buildah logout docker.pkg.github.com
